<?php

/**
 * @file
 * Contains alter hooks, validation and theme functions.
 *
 * Countdown timer field module allows you to create countdown timer
 * field to count the days, hours, minutes, and seconds until a specified
 * event.
 */

// Loading field hooks on-demand is not supported by Drupal.
module_load_include('field.inc', 'flipclock7');

/**
 * Implements hook_libraries_info().
 */
function flipclock7_libraries_info() {
  $libraries['FlipClock'] = [
    'name' => 'FlipClock',
    'vendor url' => 'http://flipclockjs.com/',
    'download url' => 'https://github.com/objectivehtml/FlipClock/releases',
    'version arguments' => [
      'file' => 'package.json',
      'pattern' => '"(\d+\.\d+\.\d+)"',
      'lines' => 5,
    ],
    'files' => [
      'css' => ['compiled/flipclock.css' => []],
      'js' => ['compiled/flipclock.min.js' => []],
    ],
  ];
  return $libraries;
}

/**
 * Implements hook_theme().
 */
function flipclock7_theme() {
  return array(
    'flipclock7_timer' => array(
      'template' => 'flipclock7-timer',
      'variables' => array(
        'timer_id' => NULL,
        'language' => NULL,
        'heading' => NULL,
      ),
    ),
  );
}
